#!/bin/sh
# Arjun's modified, mutilated, frankensien sup.
#   ___       _             _      ___  ___          _ _  __ _          _   _____ _   _______
#  / _ \     (_)           ( )     |  \/  |         | (_)/ _(_)        | | /  ___| | | | ___ \
# / /_\ \_ __ _ _   _ _ __ |/ ___  | .  . | ___   __| |_| |_ _  ___  __| | \ `--.| | | | |_/ /
# |  _  | '__| | | | | '_ \  / __| | |\/| |/ _ \ / _` | |  _| |/ _ \/ _` |  `--. \ | | |  __/
# | | | | |  | | |_| | | | | \__ \ | |  | | (_) | (_| | | | | |  __/ (_| | /\__/ / |_| | |
# \_| |_/_|  | |\__,_|_| |_| |___/ \_|  |_/\___/ \__,_|_|_| |_|\___|\__,_| \____/ \___/\_|
#           _/ |
#          |__/


echo welcome to arjuns mutilated frankestine sup

read -erp "kaunsa file ?:
    " updatefile
read -erp "kya update kiya ?:
    " update
read -erp "marker bata (format <!-- mark -->) :
    " marker

# You will want to change these variables to your needs.
# In order to cleanly use sed on a multi-line file, we have to use `tr` to
# convert newlines to a set character, then run sed, then reconvert the
# character. Unfortunately, due to a current issue in GNU's tr, characters of
# more than one byte are not functioning properly. It would be more ideal to
# use a rarer character (some random Tamil character, for example), but ^ is
# one byte.
replchar='^'
# So if you have a page with ^ in it, you'll have to change this to another
# single byte character that isn't in the page like ~ or something.

date="$(LC_TIME=en_US date '+%a, %d %b %Y %H:%M:%S %z')"
# Eh, I'm a brainlet and I'm not sure how to elegantly add in the content to
# the RSS feed without first writing it out to a file. This is because if we
# tried run, say, a sed substitute command, we'd have to escape with \
# basically every other character. If you know how to do it without creating a
# temporary file, tell me. I do the same in lb, actually.

# yes luke is surely a brainlet but good script.

temp="$(mktemp)";
trap 'rm -f "$temp"' 0 1 2 3 15	# Delete temp file after script termination.
echo "
<br><item>
<strong><update>$update<update></strong>
<br><sup><pubDate>$date</pubDate></sup>
</item><br>
" > "$temp"

sed -i "/$marker/r $temp" "$updatefile"
echo "ruk zara"
echo "kar diya saale"
